# Flora SaaS
spring.application.name=FloraSaaS

# Configuração do Banco de Dados (cria o banco automaticamente se não existir
spring.datasource.url = jdbc:mysql://localhost:3306/florasaas_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Acesso ao Banco de Dados
spring.datasource.username = root
spring.datasource.password = senaisp

# Configurações JPA
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto = update

# Exibir Queries SQL
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Admin Provisório
sistema.admin.email=admin@flora.com
sistema.admin.senha=admin_flora

# Configuração JWT
# ${JWT_SECRET}
security.jwt.secret=mysupersecretkeymysupersecretkey123!

# 60*15 // 15 minutos
security.jwt.access-expiration= 900

# 60*60*24*7 // 7 dias
security.jwt.refresh-expiration= 604800

# Configuração do contexto da aplicação para exibição da outra API & na url base
server.servlet.context-path=/florasaas

# Configuração das URLs das outras APIs
sensor.api.url=http://localhost:8081/florasaasiot
notificacao.api.url=http://localhost:8081/florasaasiot
medida.api.url=http://localhost:8081/florasaasiot

# Timeouts sugeridos
http.connect.timeout=5s
http.read.timeout=10s

# Configuração de tipo de armazenamento (Local)
storage.type=local